config/routes.rb
Rails.application.routes.draw do
  resources :padders do
  resources :requests
  end
  resources :locations, only: [:index, :show]
  
  
  get "/search", to: "padders#index", as: "search"
  get "/signups", to: "padders#new", as: "signup"
  post "/signups", to: "padders#create"
  get "/login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"
  patch "/accept/:id", to: "requests#accept"
  patch "/decline/:id", to: "requests#decline"
  post "/padders/:padder_id/requests/new", to: "requests#create"
  get "/padders/:padder_id/requests/:id", to: "requests#show"
  delete "/requests/:id", to: "requests#delete"
  get "/padders", to: "padders#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  require 'restcountry'
  has_many :padders
end

app/models/padder.rb
class Padder < ApplicationRecord
    has_secure_password
    
    validates :username, presence: true, uniqueness: true
    
    belongs_to :location
    
    has_many :requesting_padders, foreign_key: :requester_padder_id, class_name: 'Request'
    
    has_many :requestees, through: :requesting_padders, source: :requestee

    has_many :requested_padders, foreign_key: :requestee_padder_id, class_name: 'Request'
    has_many :requesters, through: :requested_padders, source: :requester
    # has_many :requests
end

app/models/request.rb
class Request < ApplicationRecord
    belongs_to :requester, class_name: 'Padder', foreign_key: :requester_padder_id
    belongs_to :requestee, class_name: 'Padder', foreign_key: :requestee_padder_id
    # has_many :padders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :set_current_padder
before_action :authorized
  private


  def set_current_padder
    @current_padder = Padder.find_by(id: session[:padder_id])
  end

  def authorized
    redirect_to login_path unless @current_padder
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index
         @locations = Location.all
    end
    
    def show
        @location = Location.find(params[:id])
    end
end

app/controllers/padders_controller.rb
class PaddersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create, :index]
    before_action :set_padder, only: [:show, :edit, :update, :delete]
    def index
        byebug
        if params[:zodiac] != ''
            @padder = Padder.where(zodiac: params[:zodiac])
        else
         @padders = Padder.all
        end
    end

    def show
    end

    def new
        @padder = Padder.new
    end

    def create
    # byebug
        @padder = Padder.new(strong_params(:username, :password, :location_id))

        @padder.username.downcase!

        if  @padder.save
            flash[:notice] = "Account Created!"
            redirect_to @padder
         else
            flash[:notice] = "Username Taken Try again!"
            redirect_to signup_path
        end
    end

    def edit
        @errors = flash[:errors]
    end

    def update

        params[:padder][:countries_visited] = params[:padder][:countries_visited].join(", ")

        if params[:padder][:countries_visited].to_s.chars.first == ","
        then params[:padder][:countries_visited] = params[:padder][:countries_visited][1..-1]
        end
        
        @padder.update(strong_params(:username, :password, :bio, :languages, :zodiac, :location_id, :countries_visited, :room_available))



        if @padder.save
            redirect_to @padder
        else
            flash[:errors]= @padder.errors.full_messages
            redirect_to edit_padder_path
        end
    end

    def delete
        @padder.destroy
        redirect_to padders_path
    end

    private

    def strong_params(*args)
    # byebug
        params.require(:padder).permit(*args)
    end

    # def zodiac_params
    # # byebug
    #     params.require(:padders).permit(:zodiac)
    # end

    def set_padder
        @padder = Padder.find(params[:id])
    end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
before_action :current_request, only:[:edit, :update, :delete, :accept, :decline, :show]
    def new
        
        @request = Request.new
        @errors = flash[:errors]
    end

    def create
        @request =
        Request.create(requestee_padder_id: params["/padders/#{params[:padder_id]}/requests/new"][:requestee_padder_id],requester_padder_id: params["/padders/#{params[:padder_id]}/requests/new"][:requester_padder_id],dates: params["/padders/#{params[:padder_id]}/requests/new"][:dates], content: params["/padders/#{params[:padder_id]}/requests/new"][:content])
        flash[:notice]= "You Accepted This Request"
        redirect_to @current_padder
    end

    def show
       
    end

    def edit
    end

    def accept
        # byebug
       @request.update(request_status: true)
        
        redirect_to @current_padder
    end

    def decline
        
        # @request.update(request_status: params["/padders/:id/requests/:id"][:request_status])
        @request.update(request_status: false)
        flash[:notice] = "You declined this request!"

        redirect_to @current_padder
    end

    def delete
        @request.destroy

        redirect_to @current_padder
    end

    private

    def current_request
        @request = 
        # byebug
        Request.find_by(params[padder_request_path(:padder_id)])
         
    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :authorized, only: [:new, :create]
    
    def new
    end

    def create
        padder = Padder.find_by(username: params[:session][:username])
    
        if padder && padder.authenticate(params[:session][:password])
    
        session[:padder_id] = padder.id
        redirect_to padder
        else
        flash[:notice] = "Login Incorrect!"
        redirect_to login_path
        end
    end

    def destroy
        session.delete(:padder_id)
        redirect_to login_path
    end
end

app/helpers/add_languages_to_locations_helper.rb
module AddLanguagesToLocationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/padders_helper.rb
module PaddersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AstropadApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <nav class="right">
          <span class="item">
            <% if @current_padder %>
              <%= link_to "User Dashboard", @current_padder  %>
              <%= link_to "Update Profile", edit_padder_path(@current_padder)%>
              <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
              <%= link_to "Search By Zodiac", search_path %>
            <% else %>
              <%= link_to "Signup", signup_path, class: "item" %>
              <%= link_to "Login", login_path, class: "item" %>
            <% end %>
          </span>
        </nav>
    <%= yield %>

  </body>
</html>
<link 

app/views/locations/index.html.erb
<h1>List of Locations</h1>

<ol>
    <% @locations.sort_by(&:country).each do |location| %>
<li>
<strong><%= link_to location.country, location  %></strong>
</li>

    <% end %>
</ol>

app/views/locations/show.html.erb
<h1><%= @location.country %></h1>
<strong><%= @location.city %></strong>

<h2>All Padders With Rooms Available in <%=@location.country  %></h2>
<ul>
<% Location.all.each do |location| %>
<% location.padders.each do |padder| %>

        <% if padder.room_available != false && padder.id != @current_padder.id && padder.location_id == @location.id%>
       <%=link_to padder.username, padder%>
        <% end %>
    <% end %>
<% end %>
</ul>

app/views/padders/edit.html.erb
  <h1>Editing <%= @padder.username %>'s Profile</h1>
  
  <%= form_for @padder do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username, autofocus: true %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
  <%= f.collection_select :location_id, Location.all, :id, :country %>
  </div>
  <div>
     <%= f.label :bio %>
     <%=f.text_area :bio %>   
  </div>
  <div>
     <%= f.label :languages%>
     <%=f.text_area :languages%>   
  </div>
  <div>
     <%= f.label :zodiac %>
     <%=f.text_field :zodiac %>   
  </div>
  <div>
     <%= f.label :countries_visited %>
     <%= f.collection_select :countries_visited, Location.order("country ASC"), :country, :country,{}, {:multiple => true} %>  
  </div>
  <div>
    <%= f.label :room_available %>
    <%= f.check_box :room_available %>
  </div>
  <div>
    <%= f.submit "Update Profile!" %>
  </div>
<% end %>

app/views/padders/index.html.erb
<h4> Search by Zodiac</h4>
<%= form_tag(padders_path, method: :get) do %>
<%= text_field_tag :zodiac, params[:zodiac] %>
<%= submit_tag ‘Search’, name: nil %>
<%end %>

app/views/padders/new.html.erb
<header>
 <h1>WELCOME TO ASTROPAD</h1>
</header>

<h1>Sign Up</h1>

<%= form_for @padder do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username, autofocus: true %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
  <%= f.collection_select :location_id, Location.all, :id, :country %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>

<%= button_to "Or Login", login_path, method: "get" %>

app/views/padders/show.html.erb
<header>
User Dashboard
</header>

<aside class="profile-card">
  <header>
    <!-- here’s the avatar -->
    <a target="_blank" href="#">
      <img src="http://lorempixel.com/150/150/people/" class="hoverZoomLink">
    </a>

    <!-- the username -->
    <h1>
      <h1><%= @padder.username.upcase %>'s Profile</h1>
          </h1>

  </header>

  <!-- bit of a bio; who are you? -->
  <div class="profile-bio">

    <p>
    BIO: 
    <%= @padder.bio %>
    </p>

  </div>

<div class="languages">

    <p>
    LANGUAGES: 
    <%= @padder.languages %>
    </p>

  </div>
<div class="zodiac">

    <p>
    ZODIAC SIGN:
    <%= @padder.zodiac %>
    </p>

  </div>
<div class="located">

    <p>
    CITY:
    <%= @padder.location.city %>
    </p>

  </div>
<div class="countries-visited">

    <p>
    COUNTRIES VISITED:
    <%= @padder.countries_visited %>
    </p>

  </div>



<section>

<% if @padder.id != @current_padder.id && @padder.room_available != false  %>
   
    <td><%= link_to "Request Room", 
    "/padders/#{@padder.id}/requests/new" %> </td>
<% end %>

<h1>Locations With Rooms Available</h1>

<p>

<% Location.all.each do |location| %>
<% location.padders.each do |padder| %>
        <% if padder.room_available != false && padder.id != @current_padder.id %>
        <%=link_to location.country, location%>
        <% end %>
    <% end %>
<% end %>
</section>

</p>
<section>
<h2><%= "Pending Requests Received" %></h2>
<ol>
 <%Request.all.each do |request| %>
      <% if @current_padder.id == request.requestee_padder_id &&@current_padder.id != request.requester_padder_id%>
       <%= link_to request.requestee_padder_id, padder_request_path(:padder_id) %></p>
       <% elsif  request.requestee_padder_id == nil%>
       <%= "No Requests For You" %>
     <% end %>
<% end %>
</ol>
</section>

<p>

<section> <h2><%= "Accepted Requests" %> </h2>

<ol>
 <%Request.all.each do |request| %>
      <% if @current_padder.id == request.requestee_padder_id && request.request_status == true %>
         <%=  request.requestee_padder_id  %>
     <% end %>
<% end %>
</ol>
</section>

</p>

<p>
<section> <h2><%= "Declined Requests" %> </h2>

<ol>
 <%Request.all.each do |request| %>
      <% if @current_padder.id == request.requestee_padder_id && request.request_status == false %>
         <%=  request.requestee_padder_id  %>
     <% end %>
<% end %>
</p>
</ol>
</section>

app/views/requests/edit.html.erb
<%= form_for(@requests) do |f| %>

<%= f.button "Accept", name: "button_action", value: "accept" %>
<%= f.button "Decline", name: "button_action", value: "decline" %>
<% end %>   
  

app/views/requests/new.html.erb
<%= form_for new_padder_request_path do |f| %>
<%= f.label :dates %> 
<%= f.text_field :dates %> 
<%= f.label :content %>
<%= f.text_area :content %>
<%= f.hidden_field :requestee_padder_id, :value => params[:padder_id]%>
<%= f.hidden_field :requester_padder_id, :value => @current_padder.id %>
<%= f.submit "Submit Request" %>
<% end %>
  

app/views/requests/show.html.erb
<h1><%= @current_padder.username %>'s Pending Requests</h1>
<div>

<div>
<%= @request.dates %>
</div>
<div>
<%= @request.content %>
<main>
<%= button_to "Accept Request", "/accept/:id", method: :patch %>
<%= button_to "Decline Request", "/decline/:id", method: :patch %>
<%= button_to "Cancel Request", "/requests/:id", method: :delete %>
</main>